### ISSUE TITLE
Untappd Token: How to retreive

### ISSUE THREAD

**Issue by petterl** [Ceerbeerus/beerbolaget#7] opened 2020-03-23 20:52 UTC
Setting up an Untappd application was easy enough, then you get the client id and secret, but what is the correct procedure to get a token? 

Should not the integration itself manage to do that or do I have to manually trigger the auth flow in [Untappd API token](https://untappd.com/api/docs#authentication), using a rest client to get it?

Please help and i can help update the documentation.

**Comment by Ceerbeerus** [comment] 2020-03-24 07:23
Hi! 
Yes, the integration should manage to handle retreval of the token on its own, but sadly I haven't had the time to implement that yet.
I belive I'll find some time quite soon.

In the meantime you could just follow the auth flow using your browser by putting the requests in the addressfield.

**Comment by JonasStenmarck** [comment] 2020-05-01 16:32
G8 app! Would love to get the untappd integration running as well. 
Can u please help me do that Untappd auth flow. 
What should I use as REDIRECT_URL and as "code"
https://untappd.com/oauth/authenticate/?client_id=CLIENTID&response_type=code&redirect_url=REDIRECT_URL

**Comment by Ceerbeerus** [comment] 2020-05-02 13:22
Thanks !

If you’re lucky I’ll have the auth flow for untappd implemented in a new release this weekend so that you dont have to do it yourself.

I’ll close this when I’m done with testing and have the release ready.

**Comment by JonasStenmarck** [comment] 2020-05-03 12:09
Wow Gr8!!! Then I'll wait *trilled* for a release with the auto token fetch and will try it out as soon as U´r release it!

**Comment by Ceerbeerus** [comment] 2020-05-04 05:50
The release is almost finished. Just one small bug caused by a timing issue left to resolve.
Documentation should be updated this evening with the release.

Would be great if you could paste any stack trace in the issue if you run in to any problems.

**Comment by Ceerbeerus** [comment] 2020-05-04 18:11
Auth flow is implemented as part of 0.4.0
Please note the breaking changes.

**Closed as completed by Ceerbeerus** 2020-05-04 18:11 UTC
